version: 2.1

executors:
  defaults_typescript:
    docker:
      - image: circleci/node:10.13.0

commands:
  install:
    steps:
      - checkout
      - attach_workspace:
          at: ~/tyrion
      - restore_cache:
          key: node-modules-cache-{{ checksum "./package-lock.json" }}
      - run:
          working_directory: .
          name: Install front dependencies
          command: npm install
      - save_cache:
          key: node-modules-cache-{{ checksum "./package-lock.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: ~/tyrion
          paths:
            - node_modules

  npm-tests:
    steps:
      - checkout
      - attach_workspace:
          at: ~/tyrion
      - run:
          name: Unit test
          command: npm run test
      - run:
          name: Run TypeScript checker
          command: npm run tsc

  npm-linter:
    steps:
      - checkout
      - attach_workspace:
          at: ~/tyrion
      - run:
          name: Run linter
          command: npm run lint

jobs:
  install-packages:
    executor: defaults_typescript
    working_directory: ~/tyrion
    steps:
      - install

  tests:
    executor: defaults_typescript
    working_directory: ~/tyrion
    environment:
      NODE_ENV: test
    steps:
      - npm-tests

  typescript-linter:
    executor: defaults_typescript
    working_directory: ~/tyrion
    environment:
      NODE_ENV: prod
    steps:
      - npm-linter

workflows:
  version: 2
  stack:
    jobs:
      - install-packages
      - tests:
          requires:
            - install-packages
      - typescript-linter:
          requires:
            - install-packages
